#!/bin/bash

# Script for generating PDF file from the PHP.earth docs repository and testing
# on Travis. It uses Docker Pandoc image.

# Documentation root directory
docs_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../"

# List of Markdown files for PDF
files=""

# Get files from given index recursively
getFiles () {
  index=( $(sed -n 's/^.*\[.*\](\(.*\))/\1/p' <"$1") )
  for file in "${index[@]}"; do
    if [[ -d "$docs_dir$file" ]]; then
      getFiles "$docs_dir$file/README.md"
    elif [[ -f "$docs_dir$file" ]]; then
      files="$files./docs$file "
    fi
  done
}

getFiles "$docs_dir/index.md"

exec 9>&1
pandoc_output=$(docker run -it \
  -v $docs_dir:/opt/docs \
  -v "$PWD":/opt/pdf \
  --name phpearth-pandoc \
  phpearth/pandoc pandoc \
    --toc \
    --pdf-engine=xelatex \
    -M title="PHP.earth documentation" \
    -M author="PHP.earth" \
    -M date="Generated on `date +%Y-%m-%d`" \
    $files \
    -o /opt/pdf/php-earth.pdf | tee /dev/fd/9)
exec 9>&-

echo "php-earth.pdf created"

exit_code="$(docker inspect -f {{.State.ExitCode}} phpearth-pandoc)"

if [[ $pandoc_output ]]; then
  exit_code=2
fi

docker rm phpearth-pandoc

exit $exit_code
