#!/bin/bash

# Script for generating PDF file from the PHP.earth docs repository and testing
# on Travis. It uses Docker Pandoc image.

# Documentation root directory
docs_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../"

# Get array of all Markdown files for PDF from index.md file
array=( $(sed -n 's/^.*\[.*\](\(.*\))/\1/p' <"$docs_dir/index.md") )

files=""
for file in "${array[@]}"
do
  files="$files./docs$file "
done;

exec 9>&1
pandoc_output=$(docker run -it \
  -v $docs_dir:/opt/docs \
  -v "$PWD":/opt/pdf \
  --name phpearth-pandoc \
  phpearth/pandoc pandoc \
    --toc \
    --latex-engine=xelatex \
    -M title="PHP.earth documentation" \
    -M author="PHP.earth" \
    -M date="Generated on `date +%Y-%m-%d`" \
    $files \
    -o /opt/pdf/php-earth.pdf | tee /dev/fd/9)
exec 9>&-

echo "php-earth.pdf created"

exit_code="$(docker inspect -f {{.State.ExitCode}} phpearth-pandoc)"

if [[ $pandoc_output ]]; then
  exit_code=2
fi

docker rm phpearth-pandoc

exit $exit_code
